server:
  port: 8088
  servlet:
    context-path: /lin
  tomcat:
    uri-encoding: UTF-8

spring:
  #数据库的配置
  datasource:
    name: dev
    url: jdbc:mysql://localhost:3306/zzzz?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xxxx
    # 使用druid数据源
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  servlet:
    multipart:
       max-file-size: 16Mb
       max-request-size: 30Mb
